### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by aryavohra** [aryavohra/Enzyme-JAX#2]
# Pipeline overview

1. EqualitySaturationPass' `runonoperation` is called by JAX. This then triggers the `module.walk` which performs a post-order traversal of the ops, calling our `dfs()` method on each of the ops.
2. `dfs()` recurses on the op's operand subgraphs and performs the following:
    * inserts the op into the `CppGraphConverter`.
    * creates a mapping from op pointers to `Box<TensorInfo>`. This is to prevent re-conversion of visited ops.
        * TODO: we need to convert this into a `llvm::DenseMap` with a proper comparator. op pointers do not biject with ops.
        * TODO: this map needs to be passed to the Rust side in some way for reconstruction. E.g the `reduce` op won't have any rewrites involving it, and it takes a function argument. Implementing a total representation of the reduce op will be challenging, so we might want to be able to reconstruct it just by referencing the original op.   
    * Note that constant tensor operands (not ConstantOps, those are handled just like normal ops) are passed as `rust::Slice` objects into the e-node's arguments.
3. Once `dfs()` traverses through the entire graph, `optimize()` method of `CppGraphConverter` is called. This internally calls `Runner`.

# TODOS
#### Rust-side
- [ ] Implement function that calls C++ with the op name and requests integer cost.

#### C++-side
- [x] Write function that takes in an op name from Rust-side caller, creates fresh op, runs `OperationTimer` on fresh op, deallocates fresh op, then returns integer cost.

### e-graph construction
ref #1.

### StableHLO graph reconstruction
- [ ] dfs through the extracted e-graph and construct `mlir::stablehlo` ops.
